# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('kolo', models.IntegerField()),
                ('misto', models.CharField(max_length=100)),
                ('tym', models.CharField(max_length=100)),
                ('L', models.FloatField()),
                ('P', models.FloatField()),
                ('L2', models.FloatField()),
                ('P2', models.FloatField()),
                ('body', models.IntegerField()),
                ('kategorie', models.CharField(max_length=100)),
            ],
        ),
    ]
