# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msl',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('rok', models.IntegerField(blank=True, db_column='ROK', null=True)),
                ('kolo', models.IntegerField(blank=True, db_column='KOLO', null=True)),
                ('misto', models.TextField(blank=True, db_column='MISTO', null=True)),
                ('tym', models.TextField(blank=True, db_column='TYM', null=True)),
                ('l', models.FloatField(blank=True, db_column='L', null=True)),
                ('p', models.FloatField(blank=True, db_column='P', null=True)),
                ('l2', models.FloatField(blank=True, db_column='L2', null=True)),
                ('p2', models.FloatField(blank=True, db_column='P2', null=True)),
                ('body', models.IntegerField(blank=True, db_column='BODY', null=True)),
                ('kategorie', models.TextField(blank=True, db_column='KATEGORIE', null=True)),
            ],
            options={
                'db_table': 'MSL',
                'managed': False,
            },
        ),
    ]
